### ISSUE TITLE
Plz Aid me to set up Oauth authentication with Asana

### ISSUE THREAD

**Issue by krishnakumarag** [Asana/oauth-examples#2]
Hi I am new to asana. I need to set up Oauth with my application. I created client id and client secret. I all the steps I am getting

home@h1-mdu1-kt144:~/Desktop/Asana/oauth-examples$ ./start ruby
bash: ./start: Permission denied

I am getting above error. any one plz provide clear details

**Comment by steveryb** [comment]
Hi @krishnakumarag, 

This usually happens when a script isn't executable. You can check the permissions with `ls -l start`. [Wikipedia](https://en.wikipedia.org/wiki/File_system_permissions) has a nice explanation of how this works. If you run `chmod +x start` does that fix the problem?
